### ISSUE TITLE
/blackbox open not working, sending error

### ISSUE THREAD

**Issue by KadTheHunter** [VideoGameSmash12/WNT#14]
I get the following error when running `/blackbox open`. It is probably an issue with my modded setup, as it doesn't occur in a fresh instance.
Hoping you can provide some insight as to what is causing it.

```
[00:27:16] [AWT-EventQueue-0/ERROR]: Uncaught exception in thread "AWT-EventQueue-0"
java.awt.HeadlessException: null
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166) ~[?:?]
	at java.awt.Window.<init>(Window.java:553) ~[?:?]
	at java.awt.Frame.<init>(Frame.java:428) ~[?:?]
	at java.awt.Frame.<init>(Frame.java:393) ~[?:?]
	at javax.swing.JFrame.<init>(JFrame.java:180) ~[?:?]
	at me.videogamesm12.wnt.blackbox.Blackbox$GUIFrame.<init>(Blackbox.java:277) ~[wnt-blackbox-2.0-alpha.3-3f53cf651ffd1b85.jar:?]
	at me.videogamesm12.wnt.blackbox.commands.BlackboxCommand.lambda$run$0(BlackboxCommand.java:56) ~[wnt-blackbox-2.0-alpha.3-3f53cf651ffd1b85.jar:?]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:722) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:716) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:741) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]
```

**Comment by VideoGameSmash12** [comment]
From what I know, Minecraft clients technically work in a "headless" mode, where a keyboard, mouse, or even monitor aren't present. To work around this, the Blackbox sets a parameter that disables headless mode (and thus allows for the window to open without issue) on startup. Apparently despite that workaround, it still thinks its in the headless mode.

My best guess as for why something like this is happening is that another mod is interfering with the parameter. What mods are you running?

**Comment by KadTheHunter** [comment]
A long list.

![image](https://user-images.githubusercontent.com/47439649/224778022-c915ef43-2f43-4cda-acf5-a208d64287b5.png)
(also mostly-up-to-date list at [@KadTheHunter/Current-Mods](https://github.com/KadTheHunter/Current-Mods), should only be missing WNT, Hotbars+ and Figura)


I will binary test it later to try and identify it (should have done it before opening, sorry), although the information you gave is very useful.

**Comment by ghost** [comment]
What JDK are you using?

**Comment by ghost** [comment]
Appears to be caused by "Custom Crosshair Mod". Doesn't look like the mod is purposefully breaking AWT. Also, you have two versions of JEI installed.

**Comment by KadTheHunter** [comment]
> What JDK are you using?

I want to say 17, but unsure, will check when I'm home

> Appears to be caused by "Custom Crosshair Mod". Doesn't look like the mod is purposefully breaking AWT.

Interesting, I'll test without that when I'm home.

> Also, you have two versions of JEI installed.

Oops 😬



Edit: Looks like CCM has no GitHub, GitLab, etc. despite claiming to be open source. Maybe I'm just missing it. Assuming it doesn't though, I guess there's no way to contact CCM about fixing this. I'll use a texture pack instead, not like I ever swap crosshairs anyway lol.

**Comment by KadTheHunter** [comment]
Confirmed, "Custom Crosshair Mod" does cause the issue.

Given CCM has no (findable) source, I guess it's not something that can be fixed.

Thank you all for the help, especially @LunaWasFlaggedAgain for identifying CCM as the problem :D
